name: Build Game

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller main.py --windowed --onefile --collect-all jaraco --add-data "sprites;sprites" --add-data "sounds;sounds" --name "Astro shooter"

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*.exe


  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build App
        run: |
          pyinstaller main.py \
            --windowed \
            --collect-all jaraco \
            --add-data "sprites:sprites" \
            --add-data "sounds:sounds" \
            --name "Astro shooter"

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/*.app
