name: Build Astro Shooter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "Building for Windows (targeting Windows 8-11)..."
            pyinstaller --onefile main.py \
              --add-data "sprites\player.png;sprites" \
              --add-data "sprites\explosion.png;sprites" \
              --add-data "sprites\powerup.png;sprites" \
              --add-data "sprites\astrode.png;sprites" \
              --add-data "sprites\lazer.png;sprites" \
              --add-data "sprites\pointer.png;sprites" \
              --add-data "sounds\explosion.wav;sounds" \
              --add-data "sounds\laserShoot.wav;sounds" \
              --add-data "sounds\powerUp.wav;sounds" \
              --add-data "sounds\background.wav;sounds"
          else
            echo "Building for macOS (targeting macOS 10.13.1 and later)..."
            export MACOSX_DEPLOYMENT_TARGET=10.13.1
            pyinstaller --onefile main.py \
              --add-data "sprites/player.png:sprites" \
              --add-data "sprites/explosion.png:sprites" \
              --add-data "sprites/powerup.png:sprites" \
              --add-data "sprites/astrode.png:sprites" \
              --add-data "sprites/lazer.png:sprites" \
              --add-data "sprites/pointer.png:sprites" \
              --add-data "sounds/explosion.wav:sounds" \
              --add-data "sounds/laserShoot.wav:sounds" \
              --add-data "sounds/powerUp.wav:sounds" \
              --add-data "sounds/background.wav:sounds"
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AstroShooter-${{ matrix.os }}
          path: dist/
